site_name: SGPI Wiki
site_url: https://rpmn0ise.github.io/wiki/
use_directory_urls: false

theme:
  name: material
  language: fr
  palette:
    - scheme: slate
      primary: black
      accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
  # Cette partie gère le bouton GitHub natif en haut à droite
  icon:
    repo: fontawesome/brands/github 

# Ces deux lignes activent le bouton GitHub dans le header
repo_name: rpmn0ise/wiki
repo_url: https://github.com/rpmn0ise/rpmn0ise.github.io



markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  # Pour ajouter Discord en haut, on peut tricher en l'ajoutant 
  # via la logique des liens de réseaux sociaux qui s'activent parfois selon le thème,
  # mais pour le header, Material utilise surtout le repo_url.
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/R2S2VZneNV
      name: Discord SGPI
    - icon: fontawesome/brands/github
      link: https://github.com/rpmn0ise/rpmn0ise.github.io
      name: GitHub
