site_name: SGPI Wiki
site_url: https://rpmn0ise.github.io/wiki/
use_directory_urls: false

theme:
  name: material
  language: fr
  palette:
    - scheme: slate
      primary: black
      accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
  # Ajout de l'icône du dépôt en haut à droite
  icon:
    repo: fontawesome/brands/github 

# Configuration du lien du dépôt (apparaît à côté de la recherche)
repo_name: rpmn0ise/wiki
repo_url: https://github.com/rpmn0ise/rpmn0ise.github.io

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/R2S2VZneNV
      name: Rejoindre notre Discord
    - icon: fontawesome/brands/github
      link: https://github.com/rpmn0ise/rpmn0ise.github.io/tree/main/wiki
      name: Voir le code source
