site_name: SGPI Wiki
site_url: https://rpmn0ise.github.io/wiki/
use_directory_urls: false

theme:
  name: material
  language: fr
  palette:
    - scheme: slate # Mode sombre profond
      primary: black
      accent: red    # Couleur "Pirate/Hacker"
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
