name: publish wiki
on:
  push:
    branches:
      - main  # Vérifiez que votre branche principale s'appelle bien main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          # Ajoutez ici d'autres extensions si nécessaire

      - name: Build Wiki
        run: |
          # On construit le wiki qui se trouve dans le dossier /wiki
          cd wiki
          mkdocs build
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # On publie le contenu du dossier 'site' généré par MkDocs
          # vers le sous-dossier 'wiki' de la branche de destination
          publish_dir: ./wiki/site
          destination_dir: wiki
          keep_files: true # TRÈS IMPORTANT : garde votre index.html actuel !
