name: publish wiki
on:
  push:
    branches:
      - main  # Vérifie que ta branche s'appelle bien 'main' et non 'master'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      - name: Build Wiki
        run: |
          cd wiki
          mkdocs build
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wiki/site
          destination_dir: wiki
          keep_files: true
